# Basic setting
c_val: 0.2
# threshold_type: [time, generation_num]
threshold_type: time
hours: 0.1
#generation_num: 300
output_dir: result/example_chro
model_setting:
  model_json: model/model_pubchemqc.tf25.json
  model_weight: model/model_pubchemqc.tf25.best.ckpt.h5
token: model/tokens_pubchemqc.pkl
reward_setting: 
  reward_module: reward.chro_reward
  reward_class: UV_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

# User setting

#parallelization strategy
leaf_parallel: False

#Gaussian setting
gau_functional: B3LYP
gau_basis: 3-21G*
gau_core_num: 10
gau_memory: 10GB
gau_option: opt uv
gau_solvent: 0
gau_error: 0
