# Basic setting
c_val: 0.1
# threshold_type: [time, generation_num]
threshold_type: time
hours: 72
# generation_num: 100
output_dir: result/IPE_C01_IPE_72h
model_setting:
  model_json: model/model.tf25.json
  model_weight: model/model.tf25.best.ckpt.h5
token: model/tokens.pkl
reward_setting: 
  reward_module: reward.IPE_reward
  reward_class: IPE_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: 100
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: True
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

#neutralization
neutralization: True
# neutralization_strategy: [Uncharger, nocharge] nocharge is Noel O’Boyle’s algorithm
neutralization_strategy: nocharge

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: True
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
#use_ring_size_filter: True
#ring_size_filter:
#  module: filter.ring_size_filter
#  class: RingSizeFilter
#  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False
# User defined filter
use_no_charge_filter: True
no_charge_filter:
  module: filter.no_charge_filter
  class: NoChargeFilter
use_aromatic_ring_filter: True
aromatic_ring_filter:
  module: filter.aromatic_ring_filter
  class: AromaticRingFilter
use_ring_size_filter: True
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  min_threshold: 5
  max_threshold: 7

# User setting

#parallelization strategy
leaf_parallel: True
qsub_parallel: True
cpu_cluster: pcc-skl # pcc-skl or pcc-normal

#Gaussian setting
gau_functional: B3LYP
gau_basis: 3-21G*
gau_total_core_num: 600
gau_option: ipe
gau_solvent: 0
gau_error: 0
