trial: 1
c_val: 1.0
hours: 0.01
expansion_threshold: 0.995
simulation_num: 3

use_lipinski_filter: True
#lipinski_filter_type: rule_of_5
use_radical_filter: True
use_hashimoto_filter: True
use_sascore_filter: True
#sa_threshold: 10.
use_ring_size_filter: True
#ring_size_threshold: 6

model_json: model/model.tf25.json
model_weight: model/model.tf25.best.ckpt.h5
output_dir: result/example01
reward_calculator: reward.logP_reward
# Need to set the same dataset used in the RNN model training.
dataset: data/250k_rndm_zinc_drugs_clean.smi