trial: 1
c_val: 1.0
hours: 0.01
expansion_threshold: 0.995
simulation_num: 3

use_lipinski_filter: True
#lipinski_filter_type: rule_of_5
use_radical_filter: True
use_hashimoto_filter: True
use_sascore_filter: True
#sa_threshold: 3.5
use_ring_size_filter: True
#ring_size_threshold: 6

model_json: model/model.tf25.json
model_weight: model/model.tf25.best.ckpt.h5
output_dir: result/example01
reward_calculator: reward.dscore_reward

# Select "max_gauss" to activate, or "min_gauss" to deactivate.
scaling_function: {"egfr": "max_gauss", "bace1": "min_gauss"}
# Set the weight for each indicator.
weight: {"egfr": 5, "bace1": 3, "sascore": 1, "qed": 1} 