# Basic setting
c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: generation_num
#hours: 0.01
generation_num: 20
output_dir: result/gnina_test/run4
model_setting:
  model_json: model/model_chembl220k.tf25.json
  model_weight: model/model_chembl220k.tf25.best.ckpt.h5
token: model/tokens_chembl220k.pkl
reward_setting:
  reward_module: reward.gnina_singularity_rmsd_reward
  reward_class: Gnina_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting:
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: True
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: True
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

leaf_parallel: True
leaf_parallel_num: 6

# User setting about gnina
gnina_bin_path: "reward/gnina.sif"
gnina_receptor: /scr/5dxh_prep_rec2.pdb
gnina_autobox_ligand: /scr/5h2_lig.mol2
gnina_cpus: 4
gnina_num_modes: 9
gnina_base_smina_affinity: -10.01144
gnina_base_cnn_affinity: 8.1709308624

# User setting about fixed structure
fixed_structure_smiles: "c3nncn3-c3ccccc3"
Crystal_structure_path: "./data/5h2_lig.mol" # Please refer to README